/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  11155111: {
    Escrow: {
      address: "0x2D789b269194AD36cC350c6954126F25579556F2",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "string",
              name: "uuid",
              type: "string",
            },
          ],
          name: "EscrowCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "string",
              name: "uuid",
              type: "string",
            },
            {
              indexed: true,
              internalType: "address",
              name: "market",
              type: "address",
            },
          ],
          name: "FulfillmentConfirmed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "string",
              name: "uuid",
              type: "string",
            },
            {
              indexed: true,
              internalType: "address",
              name: "market",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "marketShare",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "seller",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "sellerShare",
              type: "uint256",
            },
          ],
          name: "FundsDistributed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "string",
              name: "uuid",
              type: "string",
            },
            {
              indexed: true,
              internalType: "address",
              name: "receiver",
              type: "address",
            },
          ],
          name: "ProductUsedConfirmed",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "uuid",
              type: "string",
            },
          ],
          name: "confirmFulfillment",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "uuid",
              type: "string",
            },
          ],
          name: "confirmProductUsed",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "uuid",
              type: "string",
            },
            {
              internalType: "address",
              name: "_buyer",
              type: "address",
            },
            {
              internalType: "address",
              name: "_seller",
              type: "address",
            },
            {
              internalType: "address",
              name: "_receiver",
              type: "address",
            },
            {
              internalType: "address",
              name: "_market",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_contractPrice",
              type: "uint256",
            },
          ],
          name: "createEscrow",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "uuid",
              type: "string",
            },
          ],
          name: "escrowStatus",
          outputs: [
            {
              internalType: "enum Escrow.ContractStateChoices",
              name: "",
              type: "uint8",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          name: "escrows",
          outputs: [
            {
              internalType: "address",
              name: "buyer",
              type: "address",
            },
            {
              internalType: "address",
              name: "seller",
              type: "address",
            },
            {
              internalType: "address",
              name: "receiver",
              type: "address",
            },
            {
              internalType: "address",
              name: "market",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "contractPrice",
              type: "uint256",
            },
            {
              internalType: "enum Escrow.ContractStateChoices",
              name: "state",
              type: "uint8",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {},
    },
    EscrowProxy: {
      address: "0xfd2aB077a1551Ee9bfd1969a8004baA5a0546b3C",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_escrowImplementation",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "address",
              name: "newImplementation",
              type: "address",
            },
          ],
          name: "escrowImplementationUpdated",
          type: "event",
        },
        {
          stateMutability: "payable",
          type: "fallback",
        },
        {
          inputs: [],
          name: "escrowImplementation",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "latestEscrow",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_newescrowImplementation",
              type: "address",
            },
          ],
          name: "updateescrowImplementation",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
